# PostgreSQL。バージョン9.3以上がサポートされます。
#
# pgドライバをインストール：
#   gem install pg
# macOS with Homebrewの場合：
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# Windowsの場合：
#   gem install pg
#       win32ビルドを選択してください。
#       PostgreSQLをインストールし、その/binディレクトリをPATHに追加してください。
#
# Gemfileで設定
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: db              # docker-composeのサービス名
  username: postgres    # デフォルトのユーザー
  password: password    # docker-composeで設定したパスワード
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: rails_app_development

  # PostgreSQLに接続するために使用されるデータベースロールを指定します。
  # PostgreSQLで追加のロールを作成するには `$ createuser --help` を参照してください。
  # 空白のままにすると、PostgreSQLはデフォルトのロールを使用します。これは
  # Railsを実行しているオペレーティングシステムユーザーと同じ名前です。
  #username: rails_app

  # PostgreSQLロール（ユーザー名）に関連付けられたパスワード。
  #password:

  # TCPソケットで接続します。デフォルトでは省略されており、クライアントは
  # 設定不要のドメインソケットを使用します。Windowsにはドメインソケットがないため、
  # これらの行をコメント解除してください。
  #host: localhost

  # サーバーがリッスンするTCPポート。デフォルトは5432です。
  # サーバーが異なるポート番号で動作している場合は、それに応じて変更してください。
  #port: 5432

  # スキーマ検索パス。サーバーのデフォルトは$user,publicです。
  #schema_search_path: myapp,sharedapp,public

  # 最小ログレベル、昇順：
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# 警告："test"として定義されたデータベースは、"rake"を実行すると
# 開発データベースから消去され、再生成されます。
# このDBを開発または本番と同じに設定しないでください。
test:
  <<: *default
  database: rails_app_test

# config/credentials.ymlと同様に、データベースパスワードなどの機密情報を
# ソースコードに保存したくありません。ソースコードが誰かに見られた場合、
# 彼らはあなたのデータベースにアクセスできるようになります。
#
# 代わりに、アプリを起動する際にパスワードまたは完全な接続URLを環境変数として提供してください。例えば：
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# 特別なDATABASE_URL環境変数で接続URLが提供された場合、Railsは自動的に
# このファイルで提供された値の上にその設定値をマージします。または、接続URL環境変数を明示的に指定できます：
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# データベース接続設定の完全な概要については、
# https://guides.rubyonrails.org/configuring.html#configuring-a-database を参照してください。
#
production:
  <<: *default
  database: rails_app_production
  username: rails_app
  password: <%= ENV["RAILS_APP_DATABASE_PASSWORD"] %>
